Add routing info endpoint
cloudfoundry/bbs pull request #66
Opened 2023-05-02 05:28 UTC by klapkov

This PR is related to this issue: https://github.com/cloudfoundry/diego-release/issues/678. As discussed, here we introduce a new endpoint in the bbs - routing_info - which the route emitter can use when syncing to retrieve a desiredLRP that includes only the information the route emitter needs. 

In cases where there are a huge amount of security groups in a single space and multiple apps deployed in that space we notice that the network traffic consistently increases as more apps are added to a space. After investigation we found that it was due to the large amount of security groups being sent to the route emitters. 

With this approach, we see a great drop in network load when we do have such large spaces and a lot of security groups. We do not introduce a new structure of the desiredLRP as agreed previously, but just return a desiredLRP with only these fields set:

- process_guid
- domain
- log_guid
- instances
- routes
- modification_tag_epoch
- modification_tag_index
- metric_tags 

The run_info is still retrieved and decrypted since we need the metric_tags that are in it, but only the tags are returned. 

One thing to mention is that this route will be used by the route emitter only when we sync - every 60s, which still brings great improvements, but in all other cases, we still receive the desiredLRP trough the event emitted by BBS.

2023-05-02 05:35 UTC, klapkov commented
Related PR in the route emitter: https://github.com/cloudfoundry/route-emitter/pull/23

2023-05-05 08:51 UTC, PlamenDoychev requested changes

2023-05-05 08:51 UTC, PlamenDoychev commented on client.go
> +		Domain:       filter.Domain,
Perhaps 'Domain' is not required here as we request filtering based on guid only in route-emitter

2023-05-05 08:51 UTC, PlamenDoychev commented on db/sqldb/desired_lrp_db.go
> +	if filter.Domain != "" {
Perhaps this 'if' statement is not needed as we do not pass 'Domain' as filtering element in route-emitter

2023-05-05 08:51 UTC, PlamenDoychev commented on db/sqldb/desired_lrp_db_test.go
> +	FDescribe("DesiredLRPRoutingInfos", func() {
Probably forgotten fix describe 'FDescribe'

2023-05-05 08:51 UTC, PlamenDoychev commented on db/sqldb/desired_lrp_db_test.go
> +		Context("when filtering by domain", func() {
Do we need this context at all as we do not request filtering by 'Domain'?

2023-05-09 05:09 UTC, klapkov commented
@PlamenDoychev Removed the domain from the desiredLRP filter. You are right, we only filter by process_guid. Thanks

2023-05-23 18:58 UTC, geofffranks commented
@klapkov @PlamenDoychev is there any more work to be done on this PR?

2023-05-23 19:14 UTC, klapkov commented
@geofffranks Nope, this is all for this PR.

2023-05-23 19:49 UTC, geofffranks commented
Cool! If you're ready to switch your review status to approved @PlamenDoychev I'll merge this in tomorrow.

2023-05-23 22:07 UTC, merged

2023-05-23 22:07 UTC, mariash commented
Given that all the questions were resolved we merged this with @reneighbor because route-emitter needed this and it was blocking our CI.

2023-05-25 05:07 UTC, PlamenDoychev commented
Thanks @mariash @geofffranks !

Sorry we had bank holiday yesterday and did not manage to react.